import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useState } from 'react';
import LineItem from '../comps/LineItem';

export default function Home() {

  const [toDoList, setToDoList] = useState([])
  const [userInput, setUserInput] = useState('')

  const handleUserInput = (e) => {
    e.preventDefault()
    setUserInput(e.target.value);
  };

  const addNewTask = (e) => {
    e.preventDefault()
    userInput !== '' && setToDoList([...toDoList, {
      label: userInput,
      strike: false,
    }])
    setUserInput('')
  };

  const strikeHandler = (index) => {
    const newToDos = [...toDoList];
    newToDos[index].strike = !newToDos[index].strike
    setToDoList(newToDos);
  }

  const clearCheckedTasks = (e) => {
    e.preventDefault()
    const newToDos = toDoList.filter(item => item.strike === false)
    setToDoList(newToDos);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          To Do List
        </h1>
      </main>

      <div className={styles.assignTask}>
        <form>
          <input 
            type="text"
            value={userInput} 
            placeholder="Enter to do task" 
            onChange={handleUserInput} 
            required
          />
          <div className={styles.buttonContainer}>
          <button onClick={addNewTask}>Add task</button>
          <button onClick={clearCheckedTasks}>Clear checked task</button>
          <p>Click a task to check it!</p>
          </div>
        </form>
      </div>
      <div className={styles.list}>
          <ul >{ toDoList.length >= 1 ? toDoList.map((todo, index) => {
            // key shouldn't ever be index but there is no other alternative here
            return <LineItem handleStrike={strikeHandler} key={index} index={index} item={todo} />
          })
          : ""
          }
          </ul>
      </div>
    </div>
  );
}